<?php
namespace ITRocks\Framework\Tests;

use PHPUnit\Framework\TestResult;
use PHPUnit\TextUI\ResultPrinter;

/**
 * Tests HTML result printer
 */
class Tests_Html_ResultPrinter extends ResultPrinter
{

	//----------------------------------------------------------------------------------- printResult
	/**
	 * {@inheritdoc}
	 */
	public function printResult(TestResult $result): void
	{
		// TODO: Change the autogenerated stub
		parent::printResult($result);
	}

	//---------------------------------------------------------------------------------- writeNewLine
	/**
	 * Write new line : flush cache, for immediate display on browsers
	 */
	protected function writeNewLine(): void
	{
		// Keep original behavior.
		parent::writeNewLine();
		ob_flush();
		flush();
	}

}
