<?php
namespace ITRocks\Framework\Tests;

use PHPUnit_Framework_TestResult;
use PHPUnit_TextUI_ResultPrinter;

/**
 * Tests HTML result printer
 */
class Tests_Html_ResultPrinter extends PHPUnit_TextUI_ResultPrinter
{

	//----------------------------------------------------------------------------------- printResult
	/**
	 * {@inheritdoc}
	 */
	public function printResult(PHPUnit_Framework_TestResult $result)
	{
		// TODO: Change the autogenerated stub
		parent::printResult($result);
	}

	//----------------------------------------------------------------------------------------- write
	/**
	 * Writes buffer to the output and flushes to print on-the-flow.
	 *
	 * {@inheritdoc}
	 */
	public function write($buffer)
	{
		// Keep original behavior.
		parent::write($buffer);
		ob_flush();
		flush();
	}

}
