<?php
namespace ITRocks\Framework\Widget\Button;

use ITRocks\Framework\Setting;
use ITRocks\Framework\Widget\Button;

/**
 * Apply this contract to all controllers that need a getSelectionButtons() method.
 */
interface Has_Selection_Buttons
{

	//----------------------------------------------------------------------------- SELECTION_BUTTONS
	const SELECTION_BUTTONS = 'selection_buttons';

	//--------------------------------------------------------------------------- getSelectionButtons
	/**
	 * Gets the default selection buttons (selection buttons generated by the controller)
	 * This can be overridden to add default buttons to your controller
	 *
	 * @param $object     object|string The context object or class name
	 * @param $parameters array Parameters prepared for the view
	 * @param $settings   Setting\Custom\Set The controller custom settings, if set
	 * @return Button[]
	 */
	public function getSelectionButtons(
		$object, array $parameters, Setting\Custom\Set $settings = null
	);

}
