<?php
namespace ITRocks\Framework\Widget\Button;

use ITRocks\Framework\Setting\Custom_Settings;
use ITRocks\Framework\Widget\Button;

/**
 * Apply this contract to all controllers that need a getGeneralButtons() method.
 */
interface Has_General_Buttons
{

	//------------------------------------------------------------------------------- GENERAL_BUTTONS
	const GENERAL_BUTTONS = 'general_buttons';

	//----------------------------------------------------------------------------- getGeneralButtons
	/**
	 * Gets the default general buttons (general buttons generated by the controller)
	 * This can be overridden to add default buttons to your controller
	 *
	 * @param $object     object|string The context object or class name
	 * @param $parameters array Parameters prepared for the view
	 * @param $settings   Custom_Settings The controller custom settings, if set
	 * @return Button[]
	 */
	public function getGeneralButtons($object, array $parameters, Custom_Settings $settings = null);

}
