<?php
namespace ITRocks\Framework\Component\Button;

use ITRocks\Framework\Component\Button;
use ITRocks\Framework\Setting;

/**
 * Apply this contract to all controllers that need a getGeneralButtons() method.
 */
interface Has_General_Buttons
{

	//------------------------------------------------------------------------------- GENERAL_BUTTONS
	const GENERAL_BUTTONS = 'general_buttons';

	//----------------------------------------------------------------------------- getGeneralButtons
	/**
	 * Gets the default general buttons (general buttons generated by the controller)
	 * This can be overridden to add default buttons to your controller
	 *
	 * @param $object     string|object The context object or class name
	 * @param $parameters array Parameters prepared for the view
	 * @param $settings   Setting\Custom\Set|null The controller custom settings, if set
	 * @return Button[]
	 */
	public function getGeneralButtons(
		string|object $object, array $parameters, Setting\Custom\Set $settings = null
	) : array;

}
