<?php
namespace SAF\Framework\Widget\Button;

use SAF\Framework\Setting\Custom_Settings;
use SAF\Framework\Widget\Button;

/**
 * Apply this contract to all controllers that need a getSelectionButtons() method.
 */
interface Has_Selection_Buttons
{

	const SELECTION_BUTTONS = 'selection_buttons';

	//--------------------------------------------------------------------------- getSelectionButtons
	/**
	 * Gets the default selection buttons (selection buttons generated by the controller)
	 * This can be overridden to add default buttons to your controller
	 *
	 * @param $object     object|string The context object or class name
	 * @param $parameters array Parameters prepared for the view
	 * @param $settings   Custom_Settings The controller custom settings, if set
	 * @return Button[]
	 */
	public function getSelectionButtons($object, $parameters, Custom_Settings $settings = null);

}
