<?php
namespace SAF\Framework\Widget\Button;

use SAF\Framework\Setting\Custom_Settings;
use SAF\Framework\Widget\Button;

/**
 * Apply this contract to all controllers that need a getGeneralButtons() method.
 */
interface Has_General_Buttons
{

	//----------------------------------------------------------------------------- getGeneralButtons
	/**
	 * Gets the default general buttons (general buttons generated by the controller)
	 * This can be overridden to add default buttons to your controller
	 *
	 * @param $object     object|string The context object or class name
	 * @param $parameters array Parameters prepared for the view
	 * @param $settings   Custom_Settings The controller custom settings, if set
	 * @return Button[]
	 */
	public function getGeneralButtons($object, $parameters, Custom_Settings $settings = null);

}
