<?php
namespace ITRocks\Framework\View;

/**
 * The common interface to all view engines
 */
interface Engine
{

	//------------------------------------------------------------------------------------------ link
	/**
	 * Generates a link for to an object and feature, using parameters if needed
	 *
	 * @param $object     array|object|string|null linked object or class name
	 *                    Some internal calls may all this with [$class_name, $id]
	 * @param $feature    string|string[]|null linked feature name, forced if in array
	 * @param $parameters string|string[]|object|object[]|null optional parameters list
	 * @param $arguments  string|string[]|null optional arguments list
	 * @return string
	 */
	public function link(
		array|object|string|null $object,
		array|string             $feature    = null,
		array|object|string      $parameters = null,
		array|string             $arguments  = null
	) : string;

	//-------------------------------------------------------------------------------------- redirect
	/**
	 * Generates a redirection link for to an object and feature, using parameters if needed
	 *
	 * @param $link    string a link generated by self::link()
	 * @param $options array|string Single or multiple options eg Target::MAIN
	 * @return string
	 */
	public function redirect(string $link, array|string $options) : string;

	//----------------------------------------------------------------------------------- setLocation
	/**
	 * Generate code for the current view to set the current location without redirecting to it
	 *
	 * @param $uri   string
	 * @param $title string
	 * @return string
	 */
	public function setLocation(string $uri, string $title) : string;

}
