<?php
namespace ITRocks\Framework\Dao\Mysql\Information_Schema;

/**
 * Information schema : key column usage
 */
class Key_Column_Usage
{

	//---------------------------------------------------------------------------------- $COLUMN_NAME
	/**
	 * The source table column name
	 *
	 * @var string
	 */
	private $COLUMN_NAME;

	//--------------------------------------------------------------------------- $CONSTRAINT_CATALOG
	/**
	 * @values def
	 * @var string
	 */
	private $CONSTRAINT_CATALOG;

	//------------------------------------------------------------------------------ $CONSTRAINT_NAME
	/**
	 * The name of the constraint is its unique identifier
	 *
	 * @var string
	 */
	private $CONSTRAINT_NAME;

	//---------------------------------------------------------------------------- $CONSTRAINT_SCHEMA
	/**
	 * The database name which stores the constraint
	 *
	 * @var string
	 */
	private $CONSTRAINT_SCHEMA;

	//----------------------------------------------------------------------------- $ORDINAL_POSITION
	/**
	 * @var integer
	 */
	private $ORDINAL_POSITION;

	//---------------------------------------------------------------- $POSITION_IN_UNIQUE_CONSTRAINT
	/**
	 * @var integer
	 */
	private $POSITION_IN_UNIQUE_CONSTRAINT;

	//----------------------------------------------------------------------- $REFERENCED_COLUMN_NAME
	/**
	 * The foreign column name (ie always id when it is generated by the framework)
	 *
	 * @values id
	 * @var string
	 */
	private $REFERENCED_COLUMN_NAME;

	//------------------------------------------------------------------------ $REFERENCED_TABLE_NAME
	/**
	 * The foreign table name
	 *
	 * @var string
	 */
	private $REFERENCED_TABLE_NAME;

	//---------------------------------------------------------------------- $REFERENCED_TABLE_SCHEMA
	/**
	 * The foreign database name
	 *
	 * @var string
	 */
	private $REFERENCED_TABLE_SCHEMA;

	//-------------------------------------------------------------------------------- $TABLE_CATALOG
	/**
	 * @values def
	 * @var string
	 */
	private $TABLE_CATALOG;

	//----------------------------------------------------------------------------------- $TABLE_NAME
	/**
	 * The source table name
	 *
	 * @var string
	 */
	private $TABLE_NAME;

	//--------------------------------------------------------------------------------- $TABLE_SCHEMA
	/**
	 * The source database name
	 *
	 * @var string
	 */
	private $TABLE_SCHEMA;

}
